---
title: "title"
date: 2018-09-16
---

title: Computational biology for the single-cell multi-omics
author: jeongdo801
email: h.jeong@embl.de
description: > # this means to ignore newlines until "baseurl:"
  This page is to develop computational biology methodologies for the single-cell multi-omics

# social links
twitter_username: your-twitter-handle
github_username:  jeongdo801

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
